/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.houseofbadger.sudoku.main;

import java.io.File;

public class Main {
    public static void main(String[] args) {
        CommandLineHandler cmdh = new CommandLineHandler();
        cmdh.parse(args);
        Application sudokuApp = new Application();
        sudokuApp.initialize();
        sudokuApp.loadInputTable(new File("c:/temp/data"));
        sudokuApp.findSolution();
    }

}
