/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.houseofbadger.sudoku.main;

public class Main {
    public static void main(String[] args) {
        Application sudokuApp = new Application();
    }
}
