/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.houseofbadger.sudoku.main;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class SudokuResolverAppTest {
    @Test public void appHasAGreeting() {
        Main classUnderTest = new Main();
    }
}
